{
  "motors": {
    "position": {
      "maxSpeed": 3.141,
      "maxEffort": 50.0,
      "p": 20.0,
      "i": 0.0,
      "d": 0.0,
      "type": "PID"
    },
    "velocity": {
      "maxSpeed": 3.141,
      "maxEffort": 50.0,
      "type": "DC"
    }
  }
}